### ISSUE TITLE
Put some commands under contrib?

### ISSUE THREAD

**Issue by mbailey** [bash-my-aws/bash-my-aws#283]
My intention is to limit the surface area of `Bash-my-AWS`. I maintain it in my free time at no cost
and need to keep it sustainable.
I'm considering how to approach contributed commands which are for services I don't use.

- Mike

"Git is a great example of open source software that uses this convention:

https://github.com/git/git/tree/master/contrib

Here's a relevant excerpt from that README.md file:"

> Contributed Software
>
> Although these pieces are available as part of the official git source tree, they are in somewhat different status. The intention is to keep interesting tools around git here, maybe even experimental ones, to give users an easier access to them, and to give tools wider exposure, so that they can be improved faster.
>
> I am not expecting to touch these myself that much. As far as my day-to-day operation is concerned, these subdirectories are owned by their respective primary authors. I am willing to help if users of these components and the contrib/ subtree "owners" have technical/design issues to resolve, but the initiative to fix and/or enhance things must be on the side of the subtree owners.

https://softwareengineering.stackexchange.com/a/382597

**Comment by politas** [comment]
Since you've set up a dedicated GitHub organisation, you could consider adding members to the organisation to assist. It's the FOSS way of doing things!

If you want contributions to be in a separate structure from the core, it would make things easier for those of us contributing if you set up that structure. I'm happy to move my small contribution into such a structure if you wish to use it as an example.

**Comment by mbailey** [comment]
Let's keep it small/simple/sustainable
